apiVersion: v2
name: kube-prometheus-stack
version: 1.0.0-SNAPSHOT
description: Chart to deploy kube-prometheus-stack

dependencies:
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.yaml
  - name: kube-prometheus-stack
  # version: 40.2.0 
  # https://github.com/prometheus-community/helm-charts/issues/2160
  # for anthos sandbox
    version: 32.0.0
    repository: https://prometheus-community.github.io/helm-charts 